openapi: 3.0.3
info:
  title: Finance Website API
  version: "1.0.0"
servers:
  - url: http://localhost:8000
paths:
  /auth/login:
    post:
      summary: Login e emissão de JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: {type: string, format: email}
                password: {type: string, format: password}
      responses:
        '200':
          description: OK
  /bank-accounts:
    get:
      security: [{ bearerAuth: [] }]
      summary: Listar contas (lê do .env com número do banco, agência e conta)
      responses: { '200': { description: OK } }
  /bank-accounts/{id}/balance:
    get:
      security: [{ bearerAuth: [] }]
      summary: Saldo
      parameters: [{ in: path, name: id, required: true, schema: {type: string}}]
      responses: { '200': { description: OK } }
  /bank-accounts/{id}/transactions:
    get:
      security: [{ bearerAuth: [] }]
      summary: Transações
      parameters:
        - { in: path, name: id, required: true, schema: {type: string}}
        - { in: query, name: from, schema: {type: string, format: date}}
        - { in: query, name: to, schema: {type: string, format: date}}
      responses: { '200': { description: OK } }
  /payables:
    get: { security: [{ bearerAuth: [] }], summary: Listar }
    post: { security: [{ bearerAuth: [] }], summary: Criar }
  /payables/{id}:
    patch: { security: [{ bearerAuth: [] }], summary: Atualizar }
  /receipts/upload:
    post: { security: [{ bearerAuth: [] }], summary: Upload de recibo e OCR }
  /receipts/{id}:
    get: { security: [{ bearerAuth: [] }], summary: Resultado do OCR }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
